sound:
  enabled: true
  teleport-sound: 'ENTITY_ENDERMAN_TELEPORT'


messages:
  prefix: ''
  config-reloaded: '&aconfig reloaded'
  no-permission: '&cYou do not have permission to do that'
  only-players: '&cThis command can only be executed by players'
  cmd-not-exist: '&cThis command does not exist'